### ISSUE TITLE
Gateway[83AAD9] Socket connect error <class 'OSError'>

### ISSUE THREAD

**Issue by ptsa** [georgezhao2010/meizu_remoter_gateway#2]
此错误来自自定义集成。

Logger: custom_components.meizu_remoter_gateway
Source: custom_components/meizu_remoter_gateway/__init__.py:91
Integration: MEIZU Remoter Gateway (documentation, issues)
First occurred: 下午11:27:33 (1 occurrences)
Last logged: 下午11:27:33

Gateway[83AAD9] Socket connect error <class 'OSError'>

**Comment by yefoenix** [comment]
@ptsa 你好，打扰了！我也遇到了这个报错，请问是怎么解决的？
